#if !canImport(ObjectiveC)
import XCTest

extension SuperMemoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SuperMemoTests = [
        ("testEasinessFactor", testEasinessFactor),
        ("testItem", testItem),
        ("testRepetition", testRepetition),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SuperMemoTests.__allTests__SuperMemoTests),
    ]
}
#endif
